[package]
name = "rustp2p_matchmaking"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
rand = "0.9.2"
redis = { version = "0.32.7", features = ["tokio-comp", "aio"] }
tokio = { version = "1.48.0", features = ["full"] }
